version: '3.1'

services:

  consignment-cli:
    build: ./consignment-cli
    image: consignment-cli-micro
    depends_on:
      - datastore
      - vessel-service
      - consignment-service

  consignment-service:
    build:  ./consignment-service
    image: consignment-service-micro
    environment:
      DB_HOST: "mongodb://datastore:27017"
    depends_on:
      - datastore

  vessel-service:
    build: ./vessel-service
    image: vessel-service-micro
    environment:
      DB_HOST: "mongodb://datastore:27017"
    depends_on:
      - datastore

  datastore:
    image: mongo

  user-cli:
    build: ./user-cli
    image: user-cli-micro
    depends_on:
      - pgsql
      - user-service

  user-service:
    build: ./user-service
    image: user-service-micro
    depends_on:
      - pgsql

  pgsql:
    build: ./shippy-postgres
    image: shippy-postgres
    ports:
      - 5432:5432
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /home/soanni/go/src/github.com/soanni/go-microservices/part3/pgsql-data:/var/lib/postgresql/data/pgdata

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.57.0/24
