version: '3.1'

services:

  consignment-cli:
    build: ./consignment-cli
    image: consignment-cli-micro
    depends_on:
      - datastore
      - vessel-service
      - consignment-service

  consignment-service:
    build:  ./consignment-service
    image: consignment-service-micro
    environment:
      DB_HOST: "mongodb://datastore:27017"
    depends_on:
      - datastore

  vessel-service:
    build: ./vessel-service
    image: vessel-service-micro
    environment:
      DB_HOST: "mongodb://datastore:27017"
    depends_on:
      - datastore

  datastore:
    image: mongo

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.177.57.0/24
